version: '3'
services:
  database:
    image: pgautoupgrade/pgautoupgrade:latest
    container_name: pretix_db
    environment:
      - POSTGRES_USER=pretix
      - POSTGRES_PASSWORD=nvWagFGJagQ83Y6jDZv5
    volumes:
      - ./data:/data
      - ./data/conf:/etc/pretix
    networks:
      - backend_stamm
    restart: always
 
 
  redis:
    image: redis:latest
    container_name: pretix_redis
    networks:
      - backend_stamm
    restart: always
 
  pretix:
    build: ./pretix
    container_name: pretix_app
    depends_on:
      - database
      - redis
    environment:
      VIRTUAL_HOST: tickets.pfadfinderei.de
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: ticket.pfadfinderei.de
      LETSENCRYPT_EMAIL: admin@nds.pfadfinden.de
      CSRF_COOKIE_SECURE: "True"
    volumes:
      - ./data:/data
      - ./data/conf:/etc/pretix
    networks:
      - backend_stamm
      - webproxy
    restart: always
    ports:
      - 8085:80 
 
volumes:
  data_stamm:
    driver: local
  postgres_stamm:
    driver: local
  src_stamm:
    driver: local
 
networks:
  backend_stamm:
  webproxy:
